name: doctor_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  dio: ^5.5.0+1
  sizer: ^2.0.15
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.5
  intl: ^0.19.0
  pretty_dio_logger: ^1.3.1
  device_info_plus: ^11.2.1
  package_info_plus: ^8.1.3
  syncfusion_flutter_calendar: ^29.1.41
  webview_flutter: ^4.13.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/font/Poppins/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Regular.ttf
